# Generated by Django 5.1 on 2024-09-14 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
